### ISSUE TITLE
Publish on crates.io

### ISSUE THREAD

**Issue by aminya** [SunDoge/simdjson-rust#18]
It would be great to publish this crate on crates.io

Here is the docs:
https://doc.rust-lang.org/cargo/reference/publishing.html

**Comment by SunDoge** [comment]
I have just found the way to write better bindings and find https://crates.io/crates/simdjson-rust has been taken :sweat_smile:

**Comment by vilgotf** [comment]
@Redgold-labs it seems you published `simdjson-rust` on crates.io on behalf of sundodge. Could you transfer your ownership such that this project does not have to rename?

**Comment by redgold-labs** [comment]
@vilgotf yes of course I will transfer it immediately. Needed this published for testing purposes of publishing another crate, happy to transfer to whomever.

**Comment by redgold-labs** [comment]
@SunDoge I have transferred it to you and invited you to the crates.io crate -- my apologies I should have published under a unique debug name, but this was a transitive dependency of some other crate I was testing.

**Comment by SunDoge** [comment]
Done. https://crates.io/crates/simdjson-rust/0.3.0-alpha
