### ISSUE TITLE
How to iterate over objects?

### ISSUE THREAD

**Issue by richarddd** [SunDoge/simdjson-rust#27]
Hello,

I see no documentation regarding this? Array has `iter()` but what can we do for Objects?

**Comment by SunDoge** [comment]
check this https://github.com/SunDoge/simdjson-rust/blob/master/examples/issue_20.rs

**Comment by richarddd** [comment]
I’m using `dom` so `Object` does not have `iter()` 🤔

**Comment by SunDoge** [comment]
I forgot to implement some methods for `Object`. The C-API has been generated so it won't be difficult for you to open a PR to fix it. I'll check it when I'm free.
