### ISSUE TITLE
How to compile for mac m1 and linux arm64?

### ISSUE THREAD

**Issue by richarddd** [SunDoge/simdjson-rust#28]
Hi again,

When trying to compile for either M1 Mac or a generic ARM64 target i get missing symbols:

```
error: linking with `cc` failed: exit status: 1
...
ld: Undefined symbols:
            _SJ_DOM_element_get_bool, referenced from:
                simdjson_rust::dom::element::Element::get_bool::hb1204fa464618f4e in libsimdjson_rust-acd52810fd7bda8a.rlib[3](simdjson_rust-acd52810fd7bda8a.simdjson_rust.8e9a3d7c64b9bb63-cgu.0.rcgu.o)
          clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by SunDoge** [comment]
I can access the M2 macbook pro tomorrow. This may be caused by bool type mismatch in these platforms.

**Comment by SunDoge** [comment]
The current API is not very efficient. I know how to improve it but I don't have enough time :(

**Comment by aminya** [comment]
> The current API is not very efficient. I know how to improve it but I don't have enough time :(

@SunDoge could you clarify what you mean by that? Maybe others can help in improvements if they know what the inefficiencies are.

**Comment by SunDoge** [comment]
> > The current API is not very efficient. I know how to improve it but I don't have enough time :(
> 
> @SunDoge could you clarify what you mean by that? Maybe others can help in improvements if they know what the inefficiencies are.

We should only provide two kinds of API,

1. ondemand API for people want to access only part of a large json
2. dom API return a parsed object to rust, and the object can be accessed by rust directly

The overhead of crossing the boundry of C ffi is higher than I thought. Maybe we should have a dom object as 

```
struct {
JsonType json_type; // enum
union {
Array array;
Object object;
...
}
}
```

to mimic Rust's tagged union, so we don't have to call C/C++ function once after parsed.
